package test.salesforce;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * Notification Service Implementation
 *
 * This class was generated by Apache CXF 2.5.1
 * 2017-01-12T11:14:43.871-05:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "NotificationService", 
                  wsdlLocation = "file:/C:/Mulesoft/3.8/workspace1/courthouse/src/main/wsdl/ContactOut.wsdl",
                  targetNamespace = "http://soap.sforce.com/2005/09/outbound") 
public class NotificationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.sforce.com/2005/09/outbound", "NotificationService");
    public final static QName Notification = new QName("http://soap.sforce.com/2005/09/outbound", "Notification");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Mulesoft/3.8/workspace1/courthouse/src/main/wsdl/ContactOut.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NotificationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Mulesoft/3.8/workspace1/courthouse/src/main/wsdl/ContactOut.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NotificationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NotificationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NotificationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public NotificationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification() {
        return super.getPort(Notification, NotificationPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NotificationPort
     */
    @WebEndpoint(name = "Notification")
    public NotificationPort getNotification(WebServiceFeature... features) {
        return super.getPort(Notification, NotificationPort.class, features);
    }

}
